# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9179633f663b5c22849b4e2c617194ce95b13bbf6164db7eb04151f46ea00106eb43f1d1fe223638880a927594aebce6fb2291606932e8b8dfa43aa6531e7780

test:
  secret_key_base: cea8a8992ed66017fd57f2f9c02456f3230207f66b4a4b64ee6c11e723e34934fc0a79226c434ddd777c517764bf3af044ebeeff0ac148be688d37b079c04875

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
